version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile-nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./sites:/var/www/html/:z
      - ./conf:/etc/nginx/conf.d/:z

  php-fpm:
    build: 
      context: .
      dockerfile: Dockerfile-php
    image: php:7.4-fpm
    restart: always
    volumes:
      - ./sites:/var/www/html/:z

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: n3wj3rs3y
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql/:z
